/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acme_device_proximity_AcmeProximitySensor */

#ifndef _Included_com_acme_device_proximity_AcmeProximitySensor
#define _Included_com_acme_device_proximity_AcmeProximitySensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_acme_device_proximity_AcmeProximitySensor
 * Method:    open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_acme_device_proximity_AcmeProximitySensor_open
  (JNIEnv *, jclass);

/*
 * Class:     com_acme_device_proximity_AcmeProximitySensor
 * Method:    poll
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_acme_device_proximity_AcmeProximitySensor_poll
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_acme_device_proximity_AcmeProximitySensor
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_acme_device_proximity_AcmeProximitySensor_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
